/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 HARDIK
 BT18CSE118
 */

#include "factorial.h"

int *
fact_1_svc(number *argp, struct svc_req *rqstp)
{
	static int  result,n;
	printf("\nValue received from client(n) = %d \n",argp->n);
 	fflush(stdout);
 
	n=argp->n;
	// factorial logic
	result = 1;
 	
	for (int i=n;i>0;i--)
 	{
  		result=result * i;
	}
	printf("Value returned to client(fact(n)) = %d \n\n",result);
 	fflush(stdout);
	return &result;
}
