/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "chat.h"

msg *
chat_1_svc(msg *argp, struct svc_req *rqstp)
{
	static msg  result;

	char reply[500] ;
	
	printf("\nReply from client is : %s\n\n",argp->message);
	result.message[0]='\0' ;
	printf("Enter message for client : ");
	scanf("%[^\n]%*c",reply);
	strcat(result.message,reply);
	
	fflush(stdout);
	fflush(stdin);
	

	return &result;
}
