/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "factorial.h"


void
factorial_prog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	number  fact_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, FACTORIAL_PROG, FACTORIAL_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	printf("Enter number to find factorial (enter -1 to exit) : ");
	scanf("%d",&fact_1_arg.n);
	if(fact_1_arg.n==-1)
		exit(1) ;
	while(1)
	{
		result_1 = fact_1(&fact_1_arg, clnt);
		if (result_1 == (int *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		else{
			printf("\nReply from server - fact(%d) = %d \n\n",fact_1_arg.n,*result_1);
		}

		printf("Enter number to find factorial (enter -1 to exit) : ");
		scanf("%d",&fact_1_arg.n);
					
		if(fact_1_arg.n==-1)
			exit(1) ;
		
		fflush(stdin);
		fflush(stdout);
	}
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	factorial_prog_1 (host);
exit (0);
}
