/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
  HARDIK
 BT18CSE118
 */

#include "datetime.h"
#include <time.h>
char **
datetime_1_svc(void *argp, struct svc_req *rqstp)
{
	static char * result;

	time_t t;   // not a primitive datatype
    time(&t);
	result=(char*)malloc(sizeof(char)*500);
    printf("\nCurrent date and time at server is : %s\n\n", ctime(&t));
	fflush(stdout);
    strcpy(result,ctime(&t));

	return &result;
}
