/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
  HARDIK
 BT18CSE118
 */

#include "chat.h"


void
msg_prog_1(char *host)
{
	CLIENT *clnt;
	msg  *result_1;
	msg  chat_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, MSG_PROG, MSG_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	printf("Enter message for server (enter quit to exit) : ");
	scanf("%[^\n]%*c",chat_1_arg.message);
	while(1)
	{
		
		result_1 = chat_1(&chat_1_arg, clnt);
		if (result_1 == (msg *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		else{
			printf("\nReply from server is : %s\n\n",result_1->message);
		}

		printf("Enter message for server (enter quit to exit) : ");
		scanf("%[^\n]%*c",chat_1_arg.message);
				
		if(strcmp(chat_1_arg.message,"quit")==0)
			exit(1) ;
		
		fflush(stdin);
		fflush(stdout);
		
	}



#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	msg_prog_1 (host);
exit (0);
}
